// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8umgkhFV-hYjzkq18m1mI1E7AvJD8lr4',
    appId: '1:1004332655500:web:c3af3e992127d7c3b36ca9',
    messagingSenderId: '1004332655500',
    projectId: 'arthaksh-599ca',
    authDomain: 'arthaksh-599ca.firebaseapp.com',
    storageBucket: 'arthaksh-599ca.firebasestorage.app',
    measurementId: 'G-BMKELKPVL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5LRDbAVCI1T-Tj6QEeOse9awYe1ujZGA',
    appId: '1:1004332655500:android:cc35b42129cf221bb36ca9',
    messagingSenderId: '1004332655500',
    projectId: 'arthaksh-599ca',
    storageBucket: 'arthaksh-599ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2H4KvdKi84WNr5G1o8Qh1ctMKGqPoLEU',
    appId: '1:1004332655500:ios:ea7fdafb2ea9f238b36ca9',
    messagingSenderId: '1004332655500',
    projectId: 'arthaksh-599ca',
    storageBucket: 'arthaksh-599ca.firebasestorage.app',
    iosBundleId: 'com.arthaksh.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2H4KvdKi84WNr5G1o8Qh1ctMKGqPoLEU',
    appId: '1:1004332655500:ios:ea7fdafb2ea9f238b36ca9',
    messagingSenderId: '1004332655500',
    projectId: 'arthaksh-599ca',
    storageBucket: 'arthaksh-599ca.firebasestorage.app',
    iosBundleId: 'com.arthaksh.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8umgkhFV-hYjzkq18m1mI1E7AvJD8lr4',
    appId: '1:1004332655500:web:267786fb1e4c47e0b36ca9',
    messagingSenderId: '1004332655500',
    projectId: 'arthaksh-599ca',
    authDomain: 'arthaksh-599ca.firebaseapp.com',
    storageBucket: 'arthaksh-599ca.firebasestorage.app',
    measurementId: 'G-XTT5TLKXY2',
  );

}